// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzpifclomnbjqqikbgyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6cGlmY2xvbW5ianFxaWtiZ3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjA4NDQsImV4cCI6MjA1NjkzNjg0NH0.LtR8HELwKoDR4MAmvZAJbocoLZ4_Du8eHsZZJXk1v24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);